[package]
name = "deskremote-server"
version = "0.1.0"
edition = "2024"

[dependencies]
rdev = "0.5"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
bincode = "1"
mdns-sd = "0.5"
local-ip-address = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"